#' ---
#' title: "metadata.R"
#' author: "Dean Koch"
#' date: "June 25, 2020"
#' output: github_document
#' ---
#'
#' **Development version**: testing R code for preparing metadata list
#' eventually this may be turned into a public component of the rasterbc package, allowing
#' users to recreate all the steps used in preparing the dataset, and/or add their new collections
#'
#' For now it serves to record the steps for getting from the rasterbc_src repo output to the metadata_BC
#' list, which is saved as external data (in subdirectory data/) of the rasterbc package with a link in the
#' documentation to the rasterbc_src repo, where there is ample documentation of the sourcing workflow.
#'
#' This script has some information on filepaths that is specific to my workstation, so it is not intended for
#' distribution in the rasterbc package.
#'

library(here)
library(rasterbc)

# URL at FRDR where the files are currently hosted (for now, a demo version only!)
out.data.url = 'https://364cb.0ec8.dn.glob.us/1/published/publication_222/submitted_data/'

# location on my machine to look for metadata generated by the scripts in the rasterbc_src repo
src.data.dir = 'H:/git-MPB/rasterbc_src/data'

# for now, we only have the DEM data hosted
collection = 'dem'

# load the metadata and convert output filenames to web urls
cfg = readRDS(file.path(src.data.dir, paste0(collection, '.rds')))
cfg.urls = listswap_bc(cfg$out$fname$tif, 'H:/git-MPB/rasterbc/data/dem/', out.data.url)

# to do: transfer some of the metadata, add units etc

# write to data directory for package
metadata_bc = list(dem=list(url=cfg.urls))
save(metadata_bc, file='H:/git-MPB/rasterbc/data/metadata_bc.rda')

